/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package interfaz;

import clases.Cliente;
import clases.Evaluacion;
import clases.Participante;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sistema.Sistema;

/**
 *
 * @author Juan Pablo
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    
    private static Evaluacion evaluacion;
    private static int estrellas = 0;
    Sistema s;
    
    public Principal() {
        initComponents();
        s = new Sistema();
        s = new Sistema();
        evaluacion = new Evaluacion();
        
        //Se precargan datos
        populateData();
        
        //Inicialización del Combobox de clientes con uno vacío al principio
        ComboBoxClientes.setModel(new DefaultComboBoxModel(s.getClientes().toArray()));
        ComboBoxClientes.insertItemAt("------",0);
        RadioButton3.setSelected(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        ComboBoxClientes = new javax.swing.JComboBox<>();
        LabelCliente = new javax.swing.JLabel();
        LabelComentario = new javax.swing.JLabel();
        LabelMalo = new javax.swing.JLabel();
        LabelExcelente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaComentario = new javax.swing.JTextArea();
        RadioButton1 = new javax.swing.JRadioButton();
        RadioButton2 = new javax.swing.JRadioButton();
        RadioButton3 = new javax.swing.JRadioButton();
        RadioButton4 = new javax.swing.JRadioButton();
        RadioButton5 = new javax.swing.JRadioButton();
        LabelPuntuacion = new javax.swing.JLabel();
        BotonEnviar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        MenuItemSortear = new javax.swing.JMenuItem();
        MenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        LabelTitulo.setText("Formulario para evaluar la atención obtenida en el restaurante");
        jPanel1.add(LabelTitulo);
        LabelTitulo.setBounds(120, 60, 359, 16);

        ComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ComboBoxClientes);
        ComboBoxClientes.setBounds(160, 110, 64, 22);

        LabelCliente.setText("Cliente:");
        jPanel1.add(LabelCliente);
        LabelCliente.setBounds(80, 120, 44, 16);

        LabelComentario.setText("Comentario:");
        jPanel1.add(LabelComentario);
        LabelComentario.setBounds(60, 200, 71, 16);

        LabelMalo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelMalo.setText("Malo");
        jPanel1.add(LabelMalo);
        LabelMalo.setBounds(160, 150, 40, 22);

        LabelExcelente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelExcelente.setText("Excelente");
        jPanel1.add(LabelExcelente);
        LabelExcelente.setBounds(420, 150, 90, 22);

        TextAreaComentario.setColumns(20);
        TextAreaComentario.setRows(5);
        TextAreaComentario.setToolTipText("Comentario...");
        jScrollPane1.setViewportView(TextAreaComentario);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 230, 640, 173);

        buttonGroup1.add(RadioButton1);
        RadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadioButton1.setText("1");
        jPanel1.add(RadioButton1);
        RadioButton1.setBounds(200, 150, 40, 25);

        buttonGroup1.add(RadioButton2);
        RadioButton2.setText("2");
        jPanel1.add(RadioButton2);
        RadioButton2.setBounds(250, 150, 35, 25);

        buttonGroup1.add(RadioButton3);
        RadioButton3.setText("3");
        jPanel1.add(RadioButton3);
        RadioButton3.setBounds(290, 150, 35, 25);

        buttonGroup1.add(RadioButton4);
        RadioButton4.setText("4");
        jPanel1.add(RadioButton4);
        RadioButton4.setBounds(330, 150, 35, 25);

        buttonGroup1.add(RadioButton5);
        RadioButton5.setText("5");
        jPanel1.add(RadioButton5);
        RadioButton5.setBounds(370, 150, 35, 25);

        LabelPuntuacion.setText("Puntuación:");
        jPanel1.add(LabelPuntuacion);
        LabelPuntuacion.setBounds(60, 150, 67, 16);

        BotonEnviar.setText("ENVIAR");
        BotonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEnviar);
        BotonEnviar.setBounds(230, 430, 290, 60);

        MenuOpciones.setText("Opciones");

        MenuItemSortear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemSortear.setText("Sortear");
        MenuItemSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSortearActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuItemSortear);

        MenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuItemSalir);

        jMenuBar2.add(MenuOpciones);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSortearActionPerformed
        new Sortear(s).setVisible(true);
    }//GEN-LAST:event_MenuItemSortearActionPerformed

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        //Mensaje a mostrar al querer salir del sistema
        String[] opciones = {"Si","No"};
        int eleccion = JOptionPane.showOptionDialog(null,
                "¿Estás seguro que deseas salir?", "Salir del sistema",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,
                null, opciones, "No");
        if(eleccion == 0 ){
            System.exit(0);
        }else{
            
        }
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void BotonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnviarActionPerformed
        //Se envía una evaluación con/sin cliente dependiendo del seleccionado
        estrellas = Integer.parseInt(getSelectedButtonText(buttonGroup1));
        if (ComboBoxClientes.getSelectedIndex() == 0){
            s.agregarEvaluacionAnonima(estrellas, TextAreaComentario.getText());
            JOptionPane.showMessageDialog(null, "La evaluación fue enviada con "
                    + "éxito.\nLamentablemente, al no haber seleccionado cliente,"
                    + "no tienes la posibilidad de participar en nuestro sorteo.",
                    "Evaluacion enviada con éxito!",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            s.agregarEvaluacionIdentificada((Cliente) ComboBoxClientes.getSelectedItem(),
                    estrellas, TextAreaComentario.getText());
            JOptionPane.showMessageDialog(null, "La evaluación fue enviada con "
                    + "éxito.\nRecuerda que tienes la posibilidad de ser elegido"
                    + " ganador de nuestro sorteo!", "Evaluacion enviada con éxito!",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BotonEnviarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void populateData(){
        //Precarga de datos
        s.agregarCliente("Juan Pablo Gonzalez", "91827364", "098605049", "jpgonzalez@gmail.com");
        s.agregarCliente("Federico Abreu", "12345678", "09626771", "fabreu@gmail.com");
        s.agregarCliente("Adrian Perez", "876544321", "094324758", "aperez@outlook.com");
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEnviar;
    private javax.swing.JComboBox<String> ComboBoxClientes;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelComentario;
    private javax.swing.JLabel LabelExcelente;
    private javax.swing.JLabel LabelMalo;
    private javax.swing.JLabel LabelPuntuacion;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JMenuItem MenuItemSortear;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JRadioButton RadioButton2;
    private javax.swing.JRadioButton RadioButton3;
    private javax.swing.JRadioButton RadioButton4;
    private javax.swing.JRadioButton RadioButton5;
    private javax.swing.JTextArea TextAreaComentario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
